"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.12.

Docs:
- https://docs.djangoproject.com/en/3.2/topics/settings/
- https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlparse

from decouple import config

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# ==== Django core settings ====
SECRET_KEY = config("DJANGO_SECRET_KEY")
DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)

IS_DOCKER = config("DOCKER", default=False, cast=bool)

ALLOWED_HOSTS = [
    host.strip() for host in os.getenv("ALLOWED_HOSTS", "").split(",") if host.strip()
]

if not ALLOWED_HOSTS:
    if DEBUG or IS_DOCKER:
        ALLOWED_HOSTS = ["*"]

# ==== Database configuration ====
db_url = os.environ.get("DATABASE_URL") or config("DATABASE_URL", default=None)
if not db_url:
    raise ValueError("DATABASE_URL is not set!")

parsed = urlparse(db_url)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": parsed.path.lstrip("/"),
        "USER": parsed.username,
        "PASSWORD": parsed.password,
        "HOST": parsed.hostname,
        "PORT": parsed.port or 5432,
        "CONN_MAX_AGE": 600,
        "CONN_HEALTH_CHECKS": True,
    }
}

if "supabase" in (parsed.hostname or ""):
    DATABASES["default"]["OPTIONS"] = {"sslmode": "require"}

# ==== Timezone settings ====
TIME_ZONE = "Europe/Berlin"
USE_TZ = True
AUTH_USER_MODEL = "rooms.User"

# ==== Application definition ====
INSTALLED_APPS = [
    "admin_interface",
    "colorfield",  # For enhanced admin UI
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",  # Django REST Framework
    "rest_framework_simplejwt",  # JWT authentication
    "rest_framework_simplejwt.token_blacklist",  # JWT token blacklist
    "rooms",  # Custom app
    "corsheaders",  # CORS
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (  # noqa: E501
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        )
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    # Pagination settings
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    # Rate limiting: per-endpoint via `throttle_scope` + ScopedRateThrottle
    # (see rooms/views.py). No global throttle classes — authenticated CRUD
    # endpoints are not throttled; only auth/session-sensitive endpoints are.
    "DEFAULT_THROTTLE_RATES": {
        "login": "10/min",
        "token_refresh": "30/min",
        "register": "5/min",
        "join": "10/min",
        "invite_preview": "30/min",
        "change_password": "10/min",
        "regenerate_invite": "10/min",
        "token_blacklist": "30/min",
    },
    # Anon throttle buckets key on X-Forwarded-For: take the last entry —
    # the IP our proxy actually saw (spoof-proof). 1 = single proxy layer
    # (Render). Raise if another proxy (e.g. Cloudflare) is added in front.
    "NUM_PROXIES": config("NUM_PROXIES", default=1, cast=int),
}

# JWT settings for rest_framework_simplejwt
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": config("JWT_SIGNING_KEY", default=SECRET_KEY),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "TOKEN_OBTAIN_SERIALIZER": "rooms.auth_serializers.CustomTokenObtainPairSerializer",
}

# CORS settings - Restrict to frontend only
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:5173,http://localhost:5174,http://localhost:5175",
    cast=lambda v: [origin.strip() for origin in v.split(",")],
)
CORS_ALLOW_CREDENTIALS = True  # Required for cookies
# Let the browser read DRF's Retry-After header on 429 responses
CORS_EXPOSE_HEADERS = ["Retry-After"]

# CSRF trusted origins for additional security
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="http://localhost:5173,http://localhost:5174,http://localhost:5175",
    cast=lambda v: [origin.strip() for origin in v.split(",")],
)

# Cookie security settings for production
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    X_FRAME_OPTIONS = "DENY"

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
