version: '3.9'

services:
  db:
    image: postgres:15
    container_name: booking_db
    restart: always
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: booking_backend
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DOCKER: "true"
      DATABASE_URL: postgresql://admin:secret@db:5432/booking


  frontend:
    build: ./frontend
    container_name: booking_frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules  
    ports:
      - "5173:5173"
    depends_on:
      - backend
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0

volumes:
  pgdata:
