# Generated by Django 4.2.26 on 2026-01-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_booking_options_alter_booking_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name for UI (e.g., 'projector', 'wifi', 'coffee', 'capacity', 'whiteboard', 'phone', 'tv')",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Feature",
                "verbose_name_plural": "Room Features",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="room",
            name="features",
            field=models.ManyToManyField(
                blank=True,
                help_text="Amenities and equipment available in this room",
                related_name="rooms",
                to="rooms.roomfeature",
            ),
        ),
    ]
