# Generated by Django 4.2.23 on 2026-02-12 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_add_date_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s\\-\\.]+$', message='Room name can only contain letters, numbers, spaces, hyphens, and periods.')]),
        ),
    ]
