# Generated by Django 4.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0007_org_change_guards"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["start_time", "id"]},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["name"]},
        ),
    ]
